name: Bug Report
description: Report a bug
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce?
      placeholder: |
        1. Go to...
        2. Click...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Extra context
      description: Logs, screenshots, etc.
